# Generated by Django 3.0.6 on 2020-05-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200517_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contents',
            new_name='content',
        ),
    ]
